feat: revise workflow for smoke testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,9 +48,6 @@ jobs:
   run-e2e-tests:
     needs: [ filter-commit-changes ]
     if: ${{ always() && !cancelled() && needs.filter-commit-changes.outputs.has-changes-requiring-build == 'true' }}
-    concurrency:
-      group: run-e2e-tests-${{ github.workflow }}-${{ github.ref }}
-      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
     uses: ./.github/workflows/e2e-tests.yml
     with:
       e2e-tests-logs-dump: true
@@ -67,48 +64,54 @@ jobs:
       image_name: 'consensys/maru'
       push_image: false
   
+  # maru-image-smoke-test:
+  #   needs: [ build-for-testing ]
+  #   runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Download local docker image artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: linea-maru
+  #     - name: Load Docker images
+  #       run: |
+  #         pwd && ls -la && echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" &&
+  #         gunzip -c $GITHUB_WORKSPACE/linea-maru/linea-maru-docker-image.tar.gz | docker load
+  #     - name: Run Docker with maru container
+  #       run: |
+  #         MARU_TAG=${{ needs.build-for-testing.outputs.commit_tag }} make run-local-image-partial
+  #     - name: List docker containers/images
+  #       continue-on-error: true
+  #       run: |
+  #         docker ps -la && docker images
+  #         docker container ls -a
+  #         cat ./docker/initialization/genesis-maru.json
+  #     - name: Check Maru Docker logs
+  #       run: |
+  #         SEARCH_STRING="Maru is up"
+  #         TIMEOUT_SECONDS=30
+  #         INTERVAL_SECONDS=2
+  #         END_TIME=$((SECONDS + TIMEOUT_SECONDS))
+  #         while [ $SECONDS -lt $END_TIME ]; do
+  #           echo $(docker logs maru)
+  #           echo $(docker logs maru | grep -q "Maru is up")
+  #           LOGS=$(docker logs maru 2>&1)
+  #           if echo "$LOGS" | grep -q "$SEARCH_STRING"; then
+  #             echo "Found '$SEARCH_STRING' in logs. Marking job as successful."
+  #             exit 0
+  #           fi
+  #           echo "String '$SEARCH_STRING' not found yet. Retrying in $INTERVAL_SECONDS seconds..."
+  #           sleep $INTERVAL_SECONDS
+  #         done
+  #         echo "Timeout of $TIMEOUT_SECONDS seconds reached. String '$SEARCH_STRING' not found in logs."
+  #         exit 1
+
   maru-image-smoke-test:
     needs: [ build-for-testing ]
-    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Download local docker image artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: linea-maru
-      - name: Load Docker images
-        run: |
-          pwd && ls -la && echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" &&
-          gunzip -c $GITHUB_WORKSPACE/linea-maru/linea-maru-docker-image.tar.gz | docker load
-      - name: Run Docker with maru container
-        run: |
-          MARU_TAG=${{ needs.build-for-testing.outputs.commit_tag }} make run-local-image-partial
-      - name: List docker containers/images
-        continue-on-error: true
-        run: |
-          docker ps -la && docker images
-          docker container ls -a
-          cat ./docker/initialization/genesis-maru.json
-      - name: Check Maru Docker logs
-        run: |
-          SEARCH_STRING="Maru is up"
-          TIMEOUT_SECONDS=30
-          INTERVAL_SECONDS=2
-          END_TIME=$((SECONDS + TIMEOUT_SECONDS))
-          while [ $SECONDS -lt $END_TIME ]; do
-            echo $(docker logs maru)
-            echo $(docker logs maru | grep -q "Maru is up")
-            LOGS=$(docker logs maru 2>&1)
-            if echo "$LOGS" | grep -q "$SEARCH_STRING"; then
-              echo "Found '$SEARCH_STRING' in logs. Marking job as successful."
-              exit 0
-            fi
-            echo "String '$SEARCH_STRING' not found yet. Retrying in $INTERVAL_SECONDS seconds..."
-            sleep $INTERVAL_SECONDS
-          done
-          echo "Timeout of $TIMEOUT_SECONDS seconds reached. String '$SEARCH_STRING' not found in logs."
-          exit 1
+    uses: ./.github/workflows/smoke-tests.yml
+    with:
+      input: ${{ needs.build-for-testing.outputs.commit_tag }}
   
   build-and-publish:
     needs: [ maru-image-smoke-test ]
